<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="testng" duration-ms="63163" started-at="2018-09-29T08:23:11Z" finished-at="2018-09-29T08:24:14Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="63163" started-at="2018-09-29T08:23:11Z" finished-at="2018-09-29T08:24:14Z">
      <class name="demobanktest.gurutest">
        <test-method status="FAIL" signature="fg()[pri:0, instance:demobanktest.gurutest@5e5792a0]" name="fg" duration-ms="30976" started-at="2018-09-29T03:23:11Z" finished-at="2018-09-29T03:23:42Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy9.sendKeys(Unknown Source)
	at demobankpage1.bank1.poste(bank1.java:31)
	at demobanktest.gurutest.fg(gurutest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fg -->
      </class> <!-- demobanktest.gurutest -->
      <class name="demobanktest.newbanktest">
        <test-method status="PASS" signature="eat()[pri:0, instance:demobanktest.newbanktest@26653222]" name="eat" is-config="true" duration-ms="22353" started-at="2018-09-29T03:23:42Z" finished-at="2018-09-29T03:24:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- eat -->
        <test-method status="PASS" signature="ate()[pri:0, instance:demobanktest.newbanktest@26653222]" name="ate" duration-ms="9616" started-at="2018-09-29T03:24:04Z" finished-at="2018-09-29T03:24:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ate -->
        <test-method status="PASS" signature="pot()[pri:0, instance:demobanktest.newbanktest@26653222]" name="pot" is-config="true" duration-ms="140" started-at="2018-09-29T03:24:14Z" finished-at="2018-09-29T03:24:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pot -->
      </class> <!-- demobanktest.newbanktest -->
    </test> <!-- Test -->
  </suite> <!-- testng -->
</testng-results>
